{{ if .Values.dsproxy.localSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dev-backends.dsproxy.fullname" . }}
  namespace: {{ include  "dev-backends.namespace" . }}
stringData:
  PASSWORD: 'a good password'
  SALT: '12345678901234567890123456789012'
  AWS_ACCESS_KEY: {{ .Values.dsproxy.aws_access_key }}
  AWS_SECRET_KEY: {{ .Values.dsproxy.aws_secret_key }}
  AWS_URL: {{ .Values.dsproxy.aws_url }}
  AWS_REGION: {{ .Values.dsproxy.aws_region }}
  keyring.toml: |
    [keys]
    0 = "tC8AKtY34zcBArmuwcR8dakK6PhO67pv+5x3gQXG9dYQ+llXpsQZSOFIK8iPmwp3t/sLr8fqhNzNC6yiVObwY6fQDxDSDryD"
{{ end }}

