{{ if .Values.garage.enabled }}
{{- include "dev-backends.garage.validate" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-backends.garage.serviceName" . }}
  namespace: {{ include  "dev-backends.namespace" . }}
type: Opaque
stringData:
  accessKey: {{ .Values.garage.accessKey | quote }}
  secretKey: {{ .Values.garage.secretKey | quote }}
  bucket: {{ .Values.garage.bucket | quote }}
  region: {{ .Values.garage.region | quote }}
  rpcSecret: {{ include "dev-backends.garage.rpcSecret" . | quote }}
{{ end }}
