{{ if .Values.garage.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dev-backends.garage.fullname" . }}
  namespace: {{ include  "dev-backends.namespace" . }}
  labels:
    app.kubernetes.io/instance: dev-backends
    app.kubernetes.io/name: garage
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "lmdb"

    replication_factor = 1

    rpc_bind_addr = "127.0.0.1:3901"
    rpc_public_addr = "127.0.0.1:3901"

    [s3_api]
    api_bind_addr = "[::]:{{ .Values.garage.api.port }}"
    s3_region = {{ .Values.garage.region | quote }}
{{ end }}
