{{ if .Values.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dev-backends.redis.fullname" . }}
  namespace: {{ include  "dev-backends.namespace" . }}
stringData:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    {{- if and .Values.redis.username .Values.redis.password }}
    user default off
    user {{ .Values.redis.username }} on >{{ .Values.redis.password }} ~* &* +@all
    {{- end }}
{{- end }}
{{- if and .Values.redis.username .Values.redis.password }}
  username: {{ .Values.redis.username }}
  password: {{ .Values.redis.password }}
{{ end }}
