{{ if .Values.valkey.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dev-backends.valkey.fullname" . }}
  namespace: {{ include  "dev-backends.namespace" . }}
stringData:
  valkey.conf: |
    bind 0.0.0.0
    port 6379
    {{- if and .Values.valkey.username .Values.valkey.password }}
    user default off
    user {{ .Values.valkey.username }} on >{{ .Values.valkey.password }} ~* &* +@all
    {{- end }}
{{- end }}
{{- if and .Values.valkey.username .Values.valkey.password }}
  username: {{ .Values.valkey.username }}
  password: {{ .Values.valkey.password }}
{{ end }}
