{{ if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceNameOverride | default (include "dev-backends.redis.fullname" . | trunc 52 | trimSuffix "-") }}
  namespace: {{ include  "dev-backends.namespace" . }}
spec:
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: tcp-redis
  selector:
    app.kubernetes.io/instance: dev-backends
    app.kubernetes.io/name: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dev-backends.redis.fullname" . }}
  namespace: {{ include  "dev-backends.namespace" . }}
  labels:
    app.kubernetes.io/instance: dev-backends
    app.kubernetes.io/name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: dev-backends
      app.kubernetes.io/name: redis
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dev-backends
        app.kubernetes.io/name: redis
      annotations:
        configmap/hash: {{ include (print $.Template.BasePath "/redis-secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: redis
        args:
          - redis-server
          - /usr/local/etc/redis/redis.conf
        image: "redis:8.2-alpine"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: tcp-redis
        volumeMounts:
        - name: redis
          mountPath: "/usr/local/etc/redis"
          readOnly: true
      volumes:
      - name: redis
        secret:
          secretName: {{ template "dev-backends.redis.fullname" . }}
{{ end }}
