name: Release Chart
run-name: Release Chart

on:
  push:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish Helm charts
        uses: numerique-gouv/helm-gh-pages@add-overwrite-option
        with:
          charts_dir: ./charts
          linting: on
          token: ${{ secrets.GITHUB_TOKEN }}
